package cs102groupproject.SharedObjects;

public enum ActionType {
    REGISTER,
    LOGIN_WITH_GOOGLE,
    LOGOUT,
    SEND_VERIFICATION_CODE,
    VERIFY_CODE,
    FETCH_DATA,
    UPDATE_DATA,
    DELETE_DATA,
    START_GROUP_SESSION,
    JOIN_GROUP_SESSION,
    GROUP_SESSION_CREATED,
    GROUP_SESSION_JOINED,
    ERROR, 
    JOINED_GROUP_SESSION,
    LOGIN_SUCCESS,
    DEV_LOGIN,
    CREATE_GROUP_SESSION
}
